import { CubeJSWrapper } from "@utils/cubejsWrapper";
import type { Slide } from "./notationSlides";

export function getOrientYellowCornersSlides(): Slide[] {
  return [
    {
      id: "intro",
      title: "What we're aiming to achieve",
      description:
        "Congratulations! You've made it to the final lesson. This is where you'll complete the cube by orienting the yellow corners. All pieces are already in their correct positions - now we just need to rotate the corner pieces so that yellow faces up on each one. You should only be able to orbit the cube to see the complete cube from different angles.",
      allowFaceMoves: false,
      setup: (cube: CubeJSWrapper) => {
        cube.reset();
      },
    },
    {
      id: "orient-two-corners",
      title: "Orienting two corners",
      description:
        "We'll focus on re-orienting two pieces to understand the mental model. This process involves doing the Righty Algorithm (R U R' U') repeatedly until the yellow face is pointing down on that corner piece. When it is, that corner piece will be correctly oriented, and we do a D move to move onto the next corner. Because we only have two pieces to fix in this example, we only need to do this twice. Understanding this pattern is crucial for mastering corner orientation.",
      allowFaceMoves: true,
      setup: (cube: CubeJSWrapper) => {
        cube.reset();
        cube.applyMoves([
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "D",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "D'",
        ]);
      },
    },
    {
      id: "orient-three-corners",
      title: "Orienting three corners",
      description:
        "Now we'll focus on re-orienting three pieces to complete this step. This follows on from what we learned in the previous step - we repeat the same process: do the Righty Algorithm (R U R' U') until the yellow face points down, then do a D move to move to the next corner. Practice this pattern to build your understanding of the mental model.",
      allowFaceMoves: true,
      setup: (cube: CubeJSWrapper) => {
        cube.reset();
        cube.applyMoves([
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "D",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "D",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "D2",
        ]);
      },
    },
    {
      id: "orient-four-corners",
      title: "Orienting four corners",
      description:
        "Now we'll focus on re-orienting four pieces to complete this step. This follows on from what we learned in the previous steps - we repeat the same process: do the Righty Algorithm (R U R' U') until the yellow face points down, then do a D move to move to the next corner. Continue practicing this pattern to reinforce your understanding of the mental model.",
      allowFaceMoves: true,
      setup: (cube: CubeJSWrapper) => {
        cube.reset();
        cube.applyMoves([
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "D",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "D",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "D",
          "R",
          "U",
          "R'",
          "U'",
          "R",
          "U",
          "R'",
          "U'",
          "D",
        ]);
      },
    },
  ];
}
