interface CubieBorderDescriptor {
  // relative position inside cubie local space (x,y,z)
  position: [number, number, number];
  // rotation Euler in radians (x,y,z)
  rotation?: [number, number, number];
  // cylinder length (height) and radius (uniform) plus segments
  cylinder?: { radius: number; length: number; segments?: number };
  // optional color override
  color?: string;
}

const CUBIE_STYLE_MAP: {
  [key: string]: {
    cornerBuilder: string[];
    borderMeshes: CubieBorderDescriptor[];
  };
} = {
  "0,0,0": [
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
  ],
  "0,0,1": [
    "pointed",
    "rounded",
    "rounded",
    "pointed",
    "pointed",
    "rounded",
    "rounded",
    "pointed",
  ],
  "0,0,2": [
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
  ],
  "0,1,0": [
    "pointed",
    "rounded",
    "pointed",
    "rounded",
    "rounded",
    "pointed",
    "rounded",
    "pointed",
  ],
  "0,1,1": [
    "pointed",
    "rounded",
    "pointed",
    "rounded",
    "pointed",
    "rounded",
    "pointed",
    "rounded",
  ],
  "0,1,2": [
    "rounded",
    "pointed",
    "rounded",
    "pointed",
    "pointed",
    "rounded",
    "pointed",
    "rounded",
  ],
  "0,2,0": [
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
  ],
  "0,2,1": [
    "rounded",
    "pointed",
    "pointed",
    "rounded",
    "rounded",
    "pointed",
    "pointed",
    "rounded",
  ],
  "0,2,2": [
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
  ],
  "1,0,0": [
    "pointed",
    "pointed",
    "rounded",
    "rounded",
    "rounded",
    "rounded",
    "pointed",
    "pointed",
  ],
  "1,0,1": [
    "pointed",
    "pointed",
    "rounded",
    "rounded",
    "rounded",
    "rounded",
    "rounded",
    "rounded",
  ],
  "1,0,2": [
    "rounded",
    "rounded",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "rounded",
    "rounded",
  ],
  "1,1,0": [
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "rounded",
    "rounded",
    "rounded",
    "rounded",
  ],
  "1,1,1": [
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
  ],
  "1,1,2": [
    "rounded",
    "rounded",
    "rounded",
    "rounded",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
  ],
  "1,2,0": [
    "rounded",
    "rounded",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "rounded",
    "rounded",
  ],
  "1,2,1": [
    "rounded",
    "rounded",
    "pointed",
    "pointed",
    "rounded",
    "rounded",
    "pointed",
    "pointed",
  ],
  "1,2,2": [
    "pointed",
    "pointed",
    "rounded",
    "rounded",
    "rounded",
    "rounded",
    "pointed",
    "pointed",
  ],
  "2,0,0": [
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
  ],
  "2,0,1": [
    "rounded",
    "pointed",
    "pointed",
    "rounded",
    "rounded",
    "pointed",
    "pointed",
    "rounded",
  ],
  "2,0,2": [
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
  ],
  "2,1,0": [
    "rounded",
    "pointed",
    "rounded",
    "pointed",
    "pointed",
    "rounded",
    "pointed",
    "rounded",
  ],
  "2,1,1": [
    "rounded",
    "pointed",
    "rounded",
    "pointed",
    "rounded",
    "pointed",
    "rounded",
    "pointed",
  ],
  "2,1,2": [
    "pointed",
    "rounded",
    "pointed",
    "rounded",
    "rounded",
    "pointed",
    "rounded",
    "pointed",
  ],
  "2,2,0": [
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
  ],
  "2,2,1": [
    "pointed",
    "rounded",
    "rounded",
    "pointed",
    "pointed",
    "rounded",
    "rounded",
    "pointed",
  ],
  "2,2,2": [
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
    "pointed",
  ],
} as any;

export default CUBIE_STYLE_MAP;
