// Position-based move mapping - static mapping for each piece position + face + swipe direction
export const POSITION_MOVE_MAPPING = {
  // Corner pieces - 8 corners × 3 visible faces each = 24 entries
  corner_RUF_right: { up: "F'", down: "F", left: "U", right: "U'" },
  corner_RUF_top: { up: "R", down: "R'", left: "F'", right: "F" },
  corner_RUF_front: { up: "R", down: "R'", left: "U", right: "U'" },
  corner_LUF_left: { up: "F", down: "F'", left: "U", right: "U'" },
  corner_LUF_top: { up: "L'", down: "L", left: "F'", right: "F" },
  corner_LUF_front: { up: "L'", down: "L", left: "U", right: "U'" },
  corner_RUB_right: { up: "B", down: "B'", left: "U", right: "U'" },
  corner_RUB_top: { up: "R", down: "R'", left: "B", right: "B'" },
  corner_RUB_back: { up: "R'", down: "R", left: "U", right: "U'" },
  corner_LUB_left: { up: "B'", down: "B", left: "U", right: "U'" },
  corner_LUB_top: { up: "L'", down: "L", left: "B", right: "B'" },
  corner_LUB_back: { up: "L", down: "L'", left: "U", right: "U'" },
  corner_RDF_right: { up: "F'", down: "F", left: "D'", right: "D" },
  corner_RDF_bottom: { up: "R", down: "R'", left: "F", right: "F'" },
  corner_RDF_front: { up: "R", down: "R'", left: "D'", right: "D" },
  corner_LDF_left: { up: "F", down: "F'", left: "D'", right: "D" },
  corner_LDF_bottom: { up: "L'", down: "L", left: "F", right: "F'" },
  corner_LDF_front: { up: "L'", down: "L", left: "D'", right: "D" },
  corner_RDB_right: { up: "B", down: "B'", left: "D'", right: "D" },
  corner_RDB_bottom: { up: "R", down: "R'", left: "B'", right: "B" },
  corner_RDB_back: { up: "R'", down: "R", left: "D'", right: "D" },
  corner_LDB_left: { up: "B'", down: "B", left: "D'", right: "D" },
  corner_LDB_bottom: { up: "L'", down: "L", left: "B'", right: "B" },
  corner_LDB_back: { up: "L", down: "L'", left: "D'", right: "D" },

  // Edge pieces - 12 edges × 2 visible faces each = 24 entries
  edge_MUF_top: { up: "M'", down: "M", left: "F'", right: "F" },
  edge_MUF_front: { up: "M'", down: "M", left: "U", right: "U'" },
  edge_MUB_top: { up: "M'", down: "M", left: "B", right: "B'" },
  edge_MUB_back: { up: "M", down: "M'", left: "U", right: "U'" },
  edge_REF_right: { up: "F'", down: "F", left: "E'", right: "E" },
  edge_REF_front: { up: "R", down: "R'", left: "E'", right: "E" },
  edge_REB_right: { up: "B", down: "B'", left: "E'", right: "E" },
  edge_REB_back: { up: "R'", down: "R", left: "E'", right: "E" },
  edge_LEF_left: { up: "F", down: "F'", left: "E'", right: "E" },
  edge_LEF_front: { up: "L'", down: "L", left: "E'", right: "E" },
  edge_LEB_left: { up: "B'", down: "B", left: "E'", right: "E" },
  edge_LEB_back: { up: "L", down: "L'", left: "E'", right: "E" },
  edge_MDF_bottom: { up: "M'", down: "M", left: "F", right: "F'" },
  edge_MDF_front: { up: "M'", down: "M", left: "D'", right: "D" },
  edge_RDS_right: { up: "S'", down: "S", left: "D'", right: "D" },
  edge_RDS_bottom: { up: "R", down: "R'", left: "S", right: "S'" },
  edge_MDB_bottom: { up: "M'", down: "M", left: "B'", right: "B" },
  edge_MDB_back: { up: "M", down: "M'", left: "D'", right: "D" },
  edge_LDS_left: { up: "S", down: "S'", left: "D'", right: "D" },
  edge_LDS_bottom: { up: "L'", down: "L", left: "S", right: "S'" },
  edge_LUS_top: { up: "L'", down: "L", left: "S'", right: "S" },
  edge_LUS_left: { up: "S", down: "S'", left: "U", right: "U'" },
  edge_RUS_top: { up: "R", down: "R'", left: "S'", right: "S" },
  edge_RUS_right: { up: "S'", down: "S", left: "U", right: "U'" },

  // Center pieces - 6 centers × 1 visible face each = 6 entries
  center_R_right: { up: "S'", down: "S", left: "E'", right: "E" },
  center_L_left: { up: "S", down: "S'", left: "E'", right: "E" },
  center_U_top: { up: "M'", down: "M", left: "S'", right: "S" },
  center_D_bottom: { up: "M'", down: "M", left: "S", right: "S'" },
  center_F_front: { up: "M'", down: "M", left: "E'", right: "E" },
  center_B_back: { up: "M", down: "M'", left: "E'", right: "E" },
} as const;

export type PositionMoveKey = keyof typeof POSITION_MOVE_MAPPING;
